name: prostate_nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - psycopg2
  - biopython
  - python-dotenv
  - pip:
      - spacy==3.7.4
      - scispacy==0.5.4
      - negspacy==1.0.4
      - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz
      - torch
      - transformers
      - accelerate  # For faster loading
